package zahash:jsoncodegen@0.1.0;

interface sink-trait {
    use wasi:io/streams@0.2.8.{output-stream};

    resource sink {
        get-stream: func(name: string) -> result<output-stream, string>;
    }
}

interface codegen-func {
    use sink-trait.{sink};

    codegen: func(json: string, output: borrow<sink>) -> result<_, string>;
}

world sink-provider {
    export sink-trait;
}

world codegen-provider {
    import sink-trait;
    export codegen-func;
}

world orchestrator {
    import sink-trait;
    import codegen-func;
}
